package com.example.myapplication.ui

import androidx.compose.runtime.compositionLocalOf

data class Strings(
    // Home
    val appName: String,
    val trainer: String,
    val quickstart: String,
    val currentSession: String,
    val trainingLibrary: String,
    val configureTraining: String,
    val rounds: String,
    val callsRound: String,
    val moves: String,
    val historicalSubtitle: String,
    // Settings
    val settings: String,
    val close: String,
    val audio: String,
    val callVolume: String,
    val endBeep: String,
    val metronome: String,
    val tickVolume: String,
    val beatInterval: String,
    val trainingBehavior: String,
    val noImmediateRep: String,
    val noImmediateRepDesc: String,
    val manageMoves: String,
    val newMoveName: String,
    val category: String,
    val hau: String,
    val hut: String,
    val stich: String,
    val addMove: String,
    val remove: String,
    val moveDetails: String,
    val customizeMoveDetails: String,
    val customizeMoveDetailsDesc: String,
    val ttsSpeed: String,
    val ttsSpeedDesc: String,
    val language: String,
    val languageDe: String,
    val languageEn: String,
    // Setup
    val configureTrainingTitle: String,
    val back: String,
    val estimatedDuration: String,
    val seconds: String,
    val reactionInterval: String,
    val random: String,
    val minMaxSeconds: String,
    val pauseBetweenRounds: String,
    val selectMoves: String,
    val selected: String,
    val all: String,
    val haue: String,
    val huten: String,
    val stiche: String,
    val startTraining: String,
    val savePreset: String,
    val savePresetTitle: String,
    val enterPresetName: String,
    val presetName: String,
    val save: String,
    val cancel: String,
    val advancedSettings: String,
    // Presets
    val trainingLibraryTitle: String,
    val noSavedPresets: String,
    val noSavedPresetsHint: String,
    val start: String,
    val edit: String,
    val delete: String,
    val deletePreset: String,
    val deletePresetConfirm: String,
    val duration: String,
    // Training
    val pause: String,
    val resume: String,
    val stop: String,
    val finished: String,
    // Move info
    val noDescription: String,
    val noImage: String,
    val moveInfo: String,
    // Move details screen
    val moveDetailsTitle: String,
    val customizeAudioDesc: String,
    val test: String,
    val rec: String,
    val audioFile: String,
    val editInfo: String,
    val image: String,
)

val StringsDe = Strings(
    appName = "Haulauf",
    trainer = "Trainer",
    quickstart = "Quickstart",
    currentSession = "Aktuelle Session",
    trainingLibrary = "Training Library",
    configureTraining = "Training konfigurieren",
    rounds = "Runden",
    callsRound = "Calls/Runde",
    moves = "Moves",
    historicalSubtitle = "Historical European Martial Arts Training",
    settings = "Einstellungen",
    close = "Schließen",
    audio = "AUDIO",
    callVolume = "Call-Lautstärke",
    endBeep = "End-of-Window Beep",
    metronome = "Metronom",
    tickVolume = "Tick-Lautstärke",
    beatInterval = "Beat-Intervall",
    trainingBehavior = "TRAINING VERHALTEN",
    noImmediateRep = "Keine sofortige Wiederholung",
    noImmediateRepDesc = "Verhindert, dass derselbe Move zweimal hintereinander aufgerufen wird",
    manageMoves = "MOVES VERWALTEN",
    newMoveName = "Neuer Move-Name",
    category = "Kategorie",
    hau = "Hau",
    hut = "Hut",
    stich = "Stich",
    addMove = "Move hinzufügen",
    remove = "Entfernen",
    moveDetails = "MOVE DETAILS",
    customizeMoveDetails = "Move-Details anpassen",
    customizeMoveDetailsDesc = "Audio, Bilder und Beschreibungen für jeden Move bearbeiten",
    ttsSpeed = "TTS-Geschwindigkeit",
    ttsSpeedDesc = "Schnellere Ansage für Sport-Kommandos (1.0 = normal)",
    language = "Sprache",
    languageDe = "Deutsch",
    languageEn = "English",
    configureTrainingTitle = "Training konfigurieren",
    back = "Zurück",
    estimatedDuration = "Geschätzte Dauer",
    seconds = "Sekunden",
    reactionInterval = "Reaktionsintervall",
    random = "Zufall",
    minMaxSeconds = "Min / Max (Sekunden)",
    pauseBetweenRounds = "Pause zwischen Runden (Sek.)",
    selectMoves = "Moves auswählen",
    selected = "ausgewählt",
    all = "Alle",
    haue = "Haue",
    huten = "Huten",
    stiche = "Stiche",
    startTraining = "Training starten",
    savePreset = "Preset speichern",
    savePresetTitle = "Preset speichern",
    enterPresetName = "Name für dieses Preset eingeben:",
    presetName = "Preset-Name",
    save = "Speichern",
    cancel = "Abbrechen",
    advancedSettings = "Erweiterte Einstellungen",
    trainingLibraryTitle = "Training Library",
    noSavedPresets = "Keine gespeicherten Presets",
    noSavedPresetsHint = "Presets im Konfigurieren-Screen speichern",
    start = "Start",
    edit = "Bearbeiten",
    delete = "Löschen",
    deletePreset = "Preset löschen",
    deletePresetConfirm = "Möchtest du \"%s\" wirklich löschen?",
    duration = "Dauer",
    pause = "Pause",
    resume = "Fortsetzen",
    stop = "Stopp",
    finished = "Fertig",
    noDescription = "Keine Beschreibung für diesen Move.",
    noImage = "Kein Bild verfügbar",
    moveInfo = "Move-Info",
    moveDetailsTitle = "Move-Details",
    customizeAudioDesc = "Audio, Bilder und Beschreibungen für jeden Move anpassen.",
    test = "Test",
    rec = "Aufn.",
    audioFile = "Audio",
    editInfo = "Info bearbeiten",
    image = "Bild",
)

val StringsEn = Strings(
    appName = "Haulauf",
    trainer = "Trainer",
    quickstart = "Quickstart",
    currentSession = "Current Session",
    trainingLibrary = "Training Library",
    configureTraining = "Configure Training",
    rounds = "Rounds",
    callsRound = "Calls/Round",
    moves = "Moves",
    historicalSubtitle = "Historical European Martial Arts Training",
    settings = "Settings",
    close = "Close",
    audio = "AUDIO",
    callVolume = "Call Volume",
    endBeep = "End-of-Window Beep",
    metronome = "Metronome",
    tickVolume = "Tick Volume",
    beatInterval = "Beat Interval",
    trainingBehavior = "TRAINING BEHAVIOR",
    noImmediateRep = "No Immediate Repetition",
    noImmediateRepDesc = "Prevents the same move from being called twice in a row",
    manageMoves = "MANAGE MOVES",
    newMoveName = "New move name",
    category = "Category",
    hau = "Hau",
    hut = "Hut",
    stich = "Stich",
    addMove = "Add Move",
    remove = "Remove",
    moveDetails = "MOVE DETAILS",
    customizeMoveDetails = "Customize Move Details",
    customizeMoveDetailsDesc = "Edit audio, images, and descriptions for each move",
    ttsSpeed = "TTS Speed",
    ttsSpeedDesc = "Faster announcements for sport commands (1.0 = normal)",
    language = "Language",
    languageDe = "Deutsch",
    languageEn = "English",
    configureTrainingTitle = "Configure Training",
    back = "Back",
    estimatedDuration = "Estimated Duration",
    seconds = "Seconds",
    reactionInterval = "Reaction Interval",
    random = "Random",
    minMaxSeconds = "Min / Max (seconds)",
    pauseBetweenRounds = "Pause Between Rounds (sec)",
    selectMoves = "Select Moves",
    selected = "selected",
    all = "All",
    haue = "Haue",
    huten = "Huten",
    stiche = "Stiche",
    startTraining = "Start Training",
    savePreset = "Save Preset",
    savePresetTitle = "Save Preset",
    enterPresetName = "Enter a name for this preset:",
    presetName = "Preset Name",
    save = "Save",
    cancel = "Cancel",
    advancedSettings = "Advanced settings",
    trainingLibraryTitle = "Training Library",
    noSavedPresets = "No saved presets",
    noSavedPresetsHint = "Save presets from the Configure Training screen",
    start = "Start",
    edit = "Edit",
    delete = "Delete",
    deletePreset = "Delete Preset",
    deletePresetConfirm = "Are you sure you want to delete \"%s\"?",
    duration = "Duration",
    pause = "Pause",
    resume = "Resume",
    stop = "Stop",
    finished = "Finished",
    noDescription = "No description available for this move.",
    noImage = "No image available",
    moveInfo = "Move Info",
    moveDetailsTitle = "Move Details",
    customizeAudioDesc = "Customize audio, images, and descriptions for each move.",
    test = "Test",
    rec = "Rec",
    audioFile = "Audio",
    editInfo = "Edit Info",
    image = "Image",
)

val LocalStrings = compositionLocalOf { StringsDe }
