package com.example.myapplication.ui

import androidx.compose.runtime.compositionLocalOf

data class Strings(
    // Home
    val appName: String,
    val trainer: String,
    val quickstart: String,
    val currentSession: String,
    val trainingLibrary: String,
    val configureTraining: String,
    val rounds: String,
    val callsRound: String,
    val moves: String,
    val historicalSubtitle: String,
    // Settings
    val settings: String,
    val close: String,
    val audio: String,
    val callVolume: String,
    val endBeep: String,
    val metronome: String,
    val tickVolume: String,
    val beatInterval: String,
    val beatIntervalHint: String,
    val trainingBehavior: String,
    val noImmediateRep: String,
    val noImmediateRepDesc: String,
    val manageMoves: String,
    val newMoveName: String,
    val category: String,
    val hau: String,
    val hut: String,
    val stich: String,
    val addMove: String,
    val remove: String,
    val moveDetails: String,
    val customizeMoveDetails: String,
    val customizeMoveDetailsDesc: String,
    val ttsSpeed: String,
    val ttsSpeedDesc: String,
    val language: String,
    val languageDe: String,
    val languageEn: String,
    // Setup
    val configureTrainingTitle: String,
    val back: String,
    val estimatedDuration: String,
    val totalCallsAcrossRoundsFormat: String,
    val seconds: String,
    val reactionInterval: String,
    val random: String,
    val secondsRange: String,
    val minMaxSeconds: String,
    val minMaxSecondsRange: String,
    val pauseBetweenRounds: String,
    val selectMoves: String,
    val selected: String,
    val all: String,
    val haue: String,
    val huten: String,
    val stiche: String,
    val startTraining: String,
    val savePreset: String,
    val savePresetTitle: String,
    val enterPresetName: String,
    val presetName: String,
    val save: String,
    val cancel: String,
    val advancedSettings: String,
    val priority: String,
    val priorityHigh: String,
    val priorityHighest: String,
    // Presets
    val trainingLibraryTitle: String,
    val noSavedPresets: String,
    val noSavedPresetsHint: String,
    val start: String,
    val edit: String,
    val delete: String,
    val deletePreset: String,
    val deletePresetConfirm: String,
    val duration: String,
    // Training
    val pause: String,
    val resume: String,
    val stop: String,
    val finished: String,
    val starting: String,
    val unitRoundProgressFormat: String,
    val roundLabel: String,
    val pauseRoundFormat: String,
    val paused: String,
    val lastCallFormat: String,
    val countdown: String,
    val finishedExclamation: String,
    val endTraining: String,
    val wellDone: String,
    val trainingOverview: String,
    // Move info
    val noDescription: String,
    val noImage: String,
    val moveInfo: String,
    // Move details screen
    val moveDetailsTitle: String,
    val customizeAudioDesc: String,
    val customAudioPrefix: String,
    val test: String,
    val rec: String,
    val audioFile: String,
    val editInfo: String,
    val image: String,
    val reset: String,
    val audioTitleFormat: String,
    val testPlayback: String,
    val stopRecording: String,
    val newRecording: String,
    val chooseFile: String,
    val resetToDefault: String,
    val editMoveInfoTitleFormat: String,
    val descriptionLabel: String,
    val descriptionFieldLabel: String,
    val descriptionPlaceholder: String,
    val none: String,
    val metronomeSecondsPerBeat: String,
)

val StringsDe = Strings(
    appName = "Haulauf",
    trainer = "Trainer",
    quickstart = "Direkt starten",
    currentSession = "Aktuelles Training",
    trainingLibrary = "Trainings Bibliothek",
    configureTraining = "Training konfigurieren",
    rounds = "Runden",
    callsRound = "Ansagen/Runde",
    moves = "Ansagen",
    historicalSubtitle = "Historical European Martial Arts Training",
    settings = "Einstellungen",
    close = "Schliessen",
    audio = "AUDIO",
    callVolume = "Ansagen-Lautstärke",
    endBeep = "Ende des Zeitfensters Signalton",
    metronome = "Metronom",
    tickVolume = "Tick-Lautstärke",
    beatInterval = "Schläge bis zum nächsten Signalton",
    beatIntervalHint = "Stellt die Schlaganzahl indirekt ein (Reaktionszeit / Tick-Intervall).",
    trainingBehavior = "TRAINING VERHALTEN",
    noImmediateRep = "Keine direkten Wiederholungen",
    noImmediateRepDesc = "Verhindert, dass derselbe Move zweimal hintereinander aufgerufen wird",
    manageMoves = "KOMMANDOS VERWALTEN",
    newMoveName = "Neuer Kommando-Name",
    category = "Kategorie",
    hau = "Hau",
    hut = "Hut",
    stich = "Stich",
    addMove = "Kommando hinzufügen",
    remove = "Entfernen",
    moveDetails = "KOMMANDO DETAILS",
    customizeMoveDetails = "Kommando-Details anpassen",
    customizeMoveDetailsDesc = "Audio, Bilder und Beschreibungen für jedes Kommando bearbeiten",
    ttsSpeed = "TTS-Geschwindigkeit",
    ttsSpeedDesc = "Schnellere Ansage für Sport-Kommandos (1.0 = normal)",
    language = "Sprache",
    languageDe = "Deutsch",
    languageEn = "English",
    configureTrainingTitle = "Training konfigurieren",
    back = "Zurück",
    estimatedDuration = "Geschätzte Dauer",
    totalCallsAcrossRoundsFormat = "%1\$d Kommandos insgesamt in %2\$d Runden",
    seconds = "Sekunden",
    reactionInterval = "Reaktionsintervall",
    random = "Zufall",
    secondsRange = "Sekunden (0.5-5, Schritt 0.05)",
    minMaxSeconds = "Min / Max (Sekunden)",
    minMaxSecondsRange = "Min / Max (Sekunden, 0.5-5, Schritt 0.05)",
    pauseBetweenRounds = "Pause zwischen Runden (Sek.)",
    selectMoves = "Kommandos auswählen",
    selected = "ausgewählt",
    all = "Alle",
    haue = "Haue",
    huten = "Huten",
    stiche = "Stiche",
    startTraining = "Starten",
    savePreset = "Speichern",
    savePresetTitle = "Training speichern",
    enterPresetName = "Name für dieses Training eingeben:",
    presetName = "Training-Name",
    save = "Speichern",
    cancel = "Abbrechen",
    advancedSettings = "Erweiterte Einstellungen",
    priority = "Priorität",
    priorityHigh = "Hohe Prio",
    priorityHighest = "Höchste Prio",
    trainingLibraryTitle = "Trainings Bibliothek",
    noSavedPresets = "Keine gespeicherten Trainings",
    noSavedPresetsHint = "Trainings im Konfigurieren-Menü speichern",
    start = "Start",
    edit = "Bearbeiten",
    delete = "Löschen",
    deletePreset = "Training löschen",
    deletePresetConfirm = "Möchtest du \"%s\" wirklich löschen?",
    duration = "Dauer",
    pause = "Pause",
    resume = "Fortsetzen",
    stop = "Stop",
    finished = "Fertig",
    starting = "Starte...",
    unitRoundProgressFormat = "%1\$d/%2\$d  ·  %3\$s %4\$d/%5\$d",
    roundLabel = "Runde",
    pauseRoundFormat = "Pause Runde %d",
    paused = "Pausiert",
    lastCallFormat = "Letzter Ruf: %s",
    countdown = "Countdown",
    finishedExclamation = "Fertig!",
    endTraining = "Beenden",
    wellDone = "Gut gemacht!",
    trainingOverview = "Trainingsübersicht",
    noDescription = "Keine Beschreibung für dieses Kommando.",
    noImage = "Kein Bild verfügbar",
    moveInfo = "Kommando-Info",
    moveDetailsTitle = "Kommando-Details",
    customizeAudioDesc = "Audio, Bilder und Beschreibungen für jedes Kommando anpassen.",
    customAudioPrefix = "Eigene audio",
    test = "Test",
    rec = "Aufn.",
    audioFile = "Audio",
    editInfo = "Info bearbeiten",
    image = "Bild",
    reset = "Zurücksetzen",
    audioTitleFormat = "Audio: %s",
    testPlayback = "Test abspielen",
    stopRecording = "Aufnahme stoppen",
    newRecording = "Neue Aufnahme",
    chooseFile = "Datei wählen",
    resetToDefault = "Zurücksetzen auf Standard",
    editMoveInfoTitleFormat = "Kommando-Info bearbeiten: %s",
    descriptionLabel = "Beschreibung",
    descriptionFieldLabel = "Beschreibung",
    descriptionPlaceholder = "Beschreibung füer dieses Kommando eingeben",
    none = "Keine",
    metronomeSecondsPerBeat = "%.1fs pro Tick",
)

val StringsEn = Strings(
    appName = "Haulauf",
    trainer = "Trainer",
    quickstart = "Quickstart",
    currentSession = "Current Session",
    trainingLibrary = "Training Library",
    configureTraining = "Configure Training",
    rounds = "Rounds",
    callsRound = "Calls/Round",
    moves = "Moves",
    historicalSubtitle = "Historical European Martial Arts Training",
    settings = "Settings",
    close = "Close",
    audio = "AUDIO",
    callVolume = "Call Volume",
    endBeep = "End-of-Window Beep",
    metronome = "Metronome",
    tickVolume = "Tick Volume",
    beatInterval = "Beats until next signal tone",
    beatIntervalHint = "Sets the beat count indirectly (reaction window / tick interval).",
    trainingBehavior = "TRAINING BEHAVIOR",
    noImmediateRep = "No Immediate Repetition",
    noImmediateRepDesc = "Prevents the same move from being called twice in a row",
    manageMoves = "MANAGE MOVES",
    newMoveName = "New move name",
    category = "Category",
    hau = "Hau",
    hut = "Hut",
    stich = "Stich",
    addMove = "Add Move",
    remove = "Remove",
    moveDetails = "MOVE DETAILS",
    customizeMoveDetails = "Customize Move Details",
    customizeMoveDetailsDesc = "Edit audio, images, and descriptions for each move",
    ttsSpeed = "TTS Speed",
    ttsSpeedDesc = "Faster announcements for sport commands (1.0 = normal)",
    language = "Language",
    languageDe = "Deutsch",
    languageEn = "English",
    configureTrainingTitle = "Configure Training",
    back = "Back",
    estimatedDuration = "Estimated Duration",
    totalCallsAcrossRoundsFormat = "%1\$d total calls across %2\$d rounds",
    seconds = "Seconds",
    reactionInterval = "Reaction Interval",
    random = "Random",
    secondsRange = "Seconds (0.5-5, step 0.05)",
    minMaxSeconds = "Min / Max (seconds)",
    minMaxSecondsRange = "Min / Max (seconds, 0.5-5, step 0.05)",
    pauseBetweenRounds = "Pause Between Rounds (sec)",
    selectMoves = "Select Moves",
    selected = "selected",
    all = "All",
    haue = "Haue",
    huten = "Huten",
    stiche = "Stiche",
    startTraining = "Start Training",
    savePreset = "Save Preset",
    savePresetTitle = "Save Preset",
    enterPresetName = "Enter a name for this preset:",
    presetName = "Preset Name",
    save = "Save",
    cancel = "Cancel",
    advancedSettings = "Advanced settings",
    priority = "Priority",
    priorityHigh = "High priority",
    priorityHighest = "Highest priority",
    trainingLibraryTitle = "Training Library",
    noSavedPresets = "No saved presets",
    noSavedPresetsHint = "Save presets from the Configure Training screen",
    start = "Start",
    edit = "Edit",
    delete = "Delete",
    deletePreset = "Delete Preset",
    deletePresetConfirm = "Are you sure you want to delete \"%s\"?",
    duration = "Duration",
    pause = "Pause",
    resume = "Resume",
    stop = "Stop",
    finished = "Finished",
    starting = "Starting...",
    unitRoundProgressFormat = "%1\$d/%2\$d  ·  %3\$s %4\$d/%5\$d",
    roundLabel = "Round",
    pauseRoundFormat = "Round pause %d",
    paused = "Paused",
    lastCallFormat = "Last call: %s",
    countdown = "Countdown",
    finishedExclamation = "Finished!",
    endTraining = "End Session",
    wellDone = "Well done!",
    trainingOverview = "Training Summary",
    noDescription = "No description available for this move.",
    noImage = "No image available",
    moveInfo = "Move Info",
    moveDetailsTitle = "Move Details",
    customizeAudioDesc = "Customize audio, images, and descriptions for each move.",
    customAudioPrefix = "Custom audio",
    test = "Test",
    rec = "Rec",
    audioFile = "Audio",
    editInfo = "Edit Info",
    image = "Image",
    reset = "Reset",
    audioTitleFormat = "Audio: %s",
    testPlayback = "Play test",
    stopRecording = "Stop recording",
    newRecording = "New recording",
    chooseFile = "Choose file",
    resetToDefault = "Reset to default",
    editMoveInfoTitleFormat = "Edit Move Info: %s",
    descriptionLabel = "Description",
    descriptionFieldLabel = "Description",
    descriptionPlaceholder = "Enter description for this move",
    none = "None",
    metronomeSecondsPerBeat = "%.1fs per beat",
)

val LocalStrings = compositionLocalOf { StringsDe }
